### ISSUE TITLE
Meetings with DoT

### ISSUE THREAD

**Issue by VRagulina** [GSA-TTS/10x-nad-st#102]
Schedule meetings after IRL
```[tasklist]
### Tasks
- [x] Internal Review features in a backlog
- [x] Schedule meeting with DOT tech - config/arch
- [x] Meeting with Jason, Aditi, Emily, Dan (?)
- [x] Meeting with Jason about Report Assist
- [x] Create Agenda for the first meeting with Jason
- [x] Follow up meeting with Brandon with updated diagram
- [x] Schedule meeting with a Technical Interchange Meeting (TIM) with DoT cloud team
- [ ] Follow up meeting with the Tech Team
```

**Comment by VRagulina** [comment]
Follow up with Dan about 11/4 meeting. Send email to DOT

**Comment by VRagulina** [comment]
Open issue for details report meeting with Jason

**Comment by VRagulina** [comment]
Ping Scott and Tom about review
