### ISSUE TITLE
Folder upload - Data submission

### ISSUE THREAD

**Issue by VRagulina** [GSA-TTS/10x-nad-st#20]
As a NAD admin, I want to upload a folder from the Data Producer so I can proceed with the data validation workflow.
AC: Version control of submitted folders
       Ability to upload folders, including ZIP files
       Successfully scale to large datasets  

```[tasklist]
### Tasks
- [ ] Setup cloud.gov staging environment
- [ ] Validate that uploaded files are in the acceptable format
- [ ] Validate that large files can be uploaded (4gb)
- [ ] Design front end for file upload validation
```

**Comment by VRagulina** [comment]
Verify if it is done or in progress. Update Tasks
